[package]
name = "svg2emf"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
emf-core.workspace = true
vector-ir.workspace = true
glyph2path.workspace = true
roxmltree.workspace = true
svgtypes.workspace = true
kurbo.workspace = true
thiserror.workspace = true
base64.workspace = true
simplecss.workspace = true
